sudo: required
dist: xenial
group: edge

language: node_js
node_js: 11

matrix:
  include:
  - os: linux
    if: branch = master
  - os: linux
    if: branch = integration
  - os: linux
    if: branch = desktop
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: osx
    osx_image: xcode10.2
    if: branch = desktop
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: windows
    if: branch = desktop
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
    - DEBUG=electron-windows-store

branches:
  only:
  - master
  - integration
  - desktop

notifications:
  email: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

script:
  - chmod +x scripts/build.sh
  - scripts/build.sh
